#Dictionary that stores the questions and their answers
questions_data = {
    "2 + 2 x 2" : "6", 
    "(2 + 2) / 2" : "2",
    "The value of factorial of 5 (5!)" : "120",
    "10th number in the Fibonacci series" : "34",
    "Sum of angles of a triangle (in degrees)" : "180", 
    "Sum of angles of a quadrilateral (in degrees)" : "360",
    "sin²θ + cos²θ" : "1",
    "tan45°" : "1",
    "tan0°" : "0",
    "cos90°" : "0",
    "cos0°" : "1",
    "sin0°" : "0",
    "sin90°" : "1",
    "distance/time" : "speed",
    "mass x acceleration" : "force",
    "The unit of power" : "watt",
    "The SI unit of frequency" : "hertz",
    "The python method used to display information in console" : "print()",
    "The python method used to check the type of an object" : "type()",
    "The python method to remove list item by value": "remove()",
    "The python method to remove last item of list": "pop()",
    "The python method to empty the mutable objects" : "clear()",
    "The python keyword for context manager" : "with",
    "The python keyword used to define generator" : "yield",
    "The python method to find the length of the mutable objects" : "len()",
    "The python library used for data analysis" : "pandas",
    "The pandas method to display the first five rows" : "head()",
    "The pandas method to display the first n rows" : "head(n)",
    "The pandas method to display the last five rows" : "tail()",
    "The pandas method to display the last n rows" : "tail(n)",
    "The pandas method to access the values by numerical index" : "iloc()",
    "The pandas method to access the values by labels" : "loc()",
    "The pandas method to reset the index of a data frame" : "reset_index()",
    "The pandas method to combine two dataframes" : "merge()",
    "The pandas method to convert a column into datetime format" : "to_dateime()",
    "The python library used for interacting with databases" : "sqlite3",
    "The sqlite3 keyword to combine rows from two or more tables" : "join",
    "The sqlite3 keyword to skip a given number of rows" : "offset",
    "The sqlite3 method to create a connection to the database" : "connect()",
    "The sqlite3 method to retrieve all the results from a query" : "fetchall()",
}